# Generated by Django 5.0 on 2024-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phosphodb_api', '0002_alter_expressionval_log2_fc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionval',
            name='log2_fc',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
